### PR TITLE
Create shell_script

### PR DESCRIPTION
**Pull request by vinodpatill**
please review changes

### CODE REVIEW

**Comment by SakivV** [comment]
Shell script filename should have extension .sh. Please change file extension and did you run this script on your machine?

**Review by SakivV — COMMENTED** [review]
Shell script file name is not right, it should end with .sh. And did you try to run script on your machine?

**Comment by vinodpatill** [comment]
please review changes have changed file name to .sh 

THANK YOU!

**Comment by vinodpatill** [comment]
**_### I have runned the script the output is given below please review_**

#!/bin/bash
# Adding two values
((sum=25+35))
shell script

#Print the result
echo $sum
60

**Comment by vinodpatill** [comment]
**_can we change other's branch name also??_**

**Review by SakivV — APPROVED** [review]
Good Job

**Comment by vinodpatill** [comment]
THANK YOU!

**Pull request merged**
